[tool.poetry]
name = "bnbback"
version = "0.1.0"
description = ""
authors = ["신예찬 <oolo9876@yonsei.ac.kr>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
